---
site_name: Jims Obsidian Vault
site_description: Personal Obsidian Vault Published using MkDocs
site_author: Jimmy Briggs
site_url: https://vault.jimbrig.com
copyright: Copyright &copy; 2021 Jimmy Briggs
repo_url: https://github.com/jimbrig/obsidian_published
repo_name: jimbrig/obsidian_published
remote_branch: gh-pages
edit_uri: blob/main/docs/
use_directory_urls: true
plugins:
  - search
  # - autolinks
  # - section-index
  # - mkdocs-newsletter
  - roamlinks
  - awesome-pages
  - git-revision-date-localized:
      type: timeago
  - minify:
      minify_html: true
markdown_extensions:
  - toc:
      permalink: ⚑
      baselevel: 2
  - codehilite:
      linenums: false
      guess_lang: true
  - footnotes
  - abbr
  - admonition
  - meta
  - def_list
  # - pymdownx.arithmatex
  # - pymdownx.betterem:
  #     smart_enable: all
  # - pymdownx.caret
  # - pymdownx.critic
  # - pymdownx.details
  # - pymdownx.emoji:
  #     emoji_generator: "!!python/name:pymdownx.emoji.to_svg"
  # - pymdownx.inlinehilite
  # - pymdownx.magiclink
  # - pymdownx.mark
  # - pymdownx.smartsymbols
  # - pymdownx.snippets
  # - pymdownx.superfences
  # - pymdownx.tabbed
  # - pymdownx.tasklist:
  #     custom_checkbox: true
  # - pymdownx.tilde
theme:
  name: null
  custom_dir: cinder
  colorscheme: dracula
  highlightjs: true
  language: "en"
  favicon: "_attachments/obsidian.ico"
  icon:
    repo: fontawesome/brands/github
  features:
    - tabs
    - search.highlight
nav:
  - Home: index.md
  - Setup: setup.md      
  - Categories:
      - Daily Notes:
        - ... | _daily/*.md
      - Featured:
        - ... | R/*.md
        - ... | GCP/*.md
        - ... | Databases/*.md
        - ... | Windows/*.md
        - ... | WSL/*.md
        - ... | System Design/*.md
      - Everything Else:
        - ...  
  - Changelog: Changelog.md
# extra_css:
#   - stylesheets/extra.css
#   - stylesheets/links.css
extra:
  version: 1.0
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/jimbrig
    - icon: fontawesome/solid/rss
      link: https://lyz-code.github.io/blue-book/newsletter/0_newsletter_index
