name: Publish Vault
on:
  push:
    branches:
      - master
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs
      - run: pip install mkdocs-roamlinks-plugin
      - run: pip install mkdocs-awesome-pages-plugin
      - run: pip install mkdocs-git-revision-date-localized-plugin
      - run: pip install mkdocs-monorepo-plugin
      - run: pip install mkdocs-minify-plugin
      - run: mkdocs build --clean
      - run: mkdocs gh-deploy --force
